import io
from datetime import date, time

import pandas as pd
import streamlit as st

st.set_page_config(page_title="Electric Forklift Shift Register", page_icon="🧧", layout="wide")

FLT_CODES = [30, 29, 13, 14, 24, 31, 10]
STATUSES = ["Active", "Charging", "Maintenance", "Out of Service", "Other"]
COLUMNS = ["Date", "Time", "Shift", "FLT Code", "Status", "Operator", "Operation", "Charge %"]

st.markdown("""
<style>
.block-container {max-width:1200px; padding-top:2rem;}
.hero {padding:1.4rem; border:1px solid rgba(128,128,128,.25); border-radius:16px; margin-bottom:1.2rem;}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
<h1>🧧 Electric Forklift Shift Register</h1>
<p>Enter the OC shift report directly in the app — no WhatsApp copy/paste required.</p>
</div>
""", unsafe_allow_html=True)

with st.sidebar:
    st.header("Shift details")
    shift_date = st.date_input("Date", value=date.today())
    shift_time = st.time_input("Time", value=time(15, 0))
    shift_name = st.selectbox("Shift", ["Morning", "Afternoon", "Night"])
    st.divider()
    st.caption("Configured electric FLTs: " + ", ".join(map(str, FLT_CODES)))
    if st.button("Clear current register", use_container_width=True):
        st.session_state.records = pd.DataFrame(columns=COLUMNS)
        st.rerun()

if "records" not in st.session_state:
    st.session_state.records = pd.DataFrame(columns=COLUMNS)

st.info("Enter the status for each forklift at the beginning of the shift, then click **Save Shift Report**. The submitted data is immediately added to the Excel register generated by the app.")

st.subheader("📋 Electric Forklift Status")
with st.form("forklift_form"):
    rows = []
    for code in FLT_CODES:
        st.markdown(f"### 🧧 FLT {code}")
        c1, c2, c3, c4 = st.columns([1.25, 1.1, 2, 1.4])
        with c1:
            status = st.selectbox("Status", STATUSES, key=f"status_{code}")
        with c2:
            charge = st.number_input("Charge %", min_value=0, max_value=100, value=100, step=5, key=f"charge_{code}")
        with c3:
            operator = st.text_input("Operator", key=f"operator_{code}", placeholder="Operator name")
        with c4:
            operation = st.text_input("Operation", key=f"operation_{code}", placeholder="L1 / L2 / RM / inside")
        rows.append((code, status, charge, operator, operation))
        st.divider()

    submitted = st.form_submit_button("💾 SAVE SHIFT REPORT", type="primary", use_container_width=True)

if submitted:
    new_rows = [{
        "Date": shift_date.strftime("%d/%m/%Y"),
        "Time": shift_time.strftime("%I:%M %p").lstrip("0"),
        "Shift": shift_name,
        "FLT Code": code,
        "Status": status,
        "Operator": operator.strip(),
        "Operation": operation.strip(),
        "Charge %": charge,
    } for code, status, charge, operator, operation in rows]

    new_df = pd.DataFrame(new_rows, columns=COLUMNS)
    existing = st.session_state.records
    if not existing.empty:
        same_snapshot = (
            (existing["Date"] == new_df.iloc[0]["Date"]) &
            (existing["Time"] == new_df.iloc[0]["Time"]) &
            (existing["Shift"] == new_df.iloc[0]["Shift"])
        )
        existing = existing.loc[~same_snapshot]
    st.session_state.records = pd.concat([existing, new_df], ignore_index=True)
    st.session_state.last_saved_key = (new_df.iloc[0]["Date"], new_df.iloc[0]["Time"], new_df.iloc[0]["Shift"])
    st.success("✅ Shift report saved. The Excel register below now contains the entered data.")

if not st.session_state.records.empty:
    df = st.session_state.records.copy()
    latest_key = st.session_state.get("last_saved_key")
    if latest_key:
        latest = df[(df["Date"] == latest_key[0]) & (df["Time"] == latest_key[1]) & (df["Shift"] == latest_key[2])].copy()
    else:
        latest = df.tail(len(FLT_CODES)).copy()

    total = len(latest)
    active = int((latest["Status"].str.lower() == "active").sum())
    charging = int((latest["Status"].str.lower() == "charging").sum())
    assigned = int(latest["Operator"].fillna("").str.strip().ne("").sum())
    missing = total - assigned
    avg_charge = latest["Charge %"].mean()

    st.divider()
    st.subheader("📟 Terminal Summary — Latest Shift")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Total FLTs", total)
    c2.metric("Active", active)
    c3.metric("Charging", charging)
    c4.metric("Avg. Charge", f"{avg_charge:.1f}%")
    c5.metric("Operator Missing", missing)

    st.code(f"""=== ELECTRIC FORKLIFT SHIFT STATUS ===
DATE : {latest.iloc[0]['Date']}    TIME : {latest.iloc[0]['Time']}
SHIFT: {latest.iloc[0]['Shift']}
----------------------------------------
TOTAL FLT        : {total}
ACTIVE           : {active}
CHARGING         : {charging}
AVG CHARGE       : {avg_charge:.1f}%
OPERATOR ASSIGNED: {assigned}
OPERATOR MISSING : {missing}
----------------------------------------""")

    missing_codes = latest.loc[latest["Operator"].fillna("").str.strip().eq(""), "FLT Code"].tolist()
    if missing_codes:
        st.warning("⚠️ Operator not assigned: " + ", ".join(map(str, missing_codes)))

    st.subheader("📋 Latest Shift Register")
    st.dataframe(latest, use_container_width=True, hide_index=True)

    st.subheader("📚 Recorded Shift History")
    st.dataframe(df, use_container_width=True, hide_index=True)

    summary_rows = [
        ["Date", latest.iloc[0]["Date"]],
        ["Time", latest.iloc[0]["Time"]],
        ["Shift", latest.iloc[0]["Shift"]],
        ["Total Electric FLTs", total],
        ["Active", active],
        ["Charging", charging],
        ["Average Charge %", round(avg_charge, 1)],
        ["Operators Assigned", assigned],
        ["Operators Missing", missing],
    ]
    summary_df = pd.DataFrame(summary_rows, columns=["Metric", "Value"])

    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Shift Register")
        summary_df.to_excel(writer, index=False, sheet_name="Latest Summary")
        for sheet in writer.book.worksheets:
            sheet.freeze_panes = "A2"
            sheet.auto_filter.ref = sheet.dimensions
            for col in sheet.columns:
                values = [len(str(cell.value or "")) for cell in col]
                sheet.column_dimensions[col[0].column_letter].width = min(max(max(values) + 2, 10), 28)
    output.seek(0)

    st.download_button(
        "📥 DOWNLOAD EXCEL REGISTER",
        data=output,
        file_name="electric_forklift_shift_register.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        use_container_width=True,
    )

st.caption("The form records the shift snapshot directly. The Excel export contains the complete register plus the latest shift summary.")
