create table if not exists public.forklift_shift_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Date" date not null,
  "Time" time not null,
  "Shift" text not null,
  "FLT Code" text not null,
  "Status" text not null,
  "Operator" text default '',
  "Operation" text default '',
  "Charge %" numeric(5,2) not null check ("Charge %" >= 0 and "Charge %" <= 100)
);

alter table public.forklift_shift_records enable row level security;

-- For the first private prototype, use the Supabase service role key only in
-- Streamlit secrets. Do NOT put that key in GitHub or client-side code.
create policy "service role access" on public.forklift_shift_records
  for all to service_role using (true) with check (true);
